name: '{{ NAME }}'
description: '{{ DESCRIPTION }}'
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  working-directory:
    description: The working directory where Terraform will be executed
    required: false
  subject:
    description: The subject to greet
    required: false
    default: World

runs:
  using: composite
  steps:
    - name: '{{ NAME }}'
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_ACTION_INPUT_subject: ${{ inputs.subject }}
      run: |
        # '{{ NAME }}'
        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" -Verbose


    runs-on: ubuntu-latest
    steps:
    - name: Get PR info
      id: pr
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |

        
    - name: Download Artifact from CI
      uses: actions/download-artifact@v4
      with:
        name: docs
        github-token: ${{ github.token }}    
        run-id:  ${{ steps.pr.outputs.run-id }}